import type { BoardVoteItem } from "../types";

/** Community Outreach Network — edit this file to add or change vote items for this archetype. */
export const communityBoardVotes: BoardVoteItem[] = [
  {
    id: "cv-1",
    meetingId: "meet-community-may2026",
    title: "Approve new board member slate",
    category: "Governance",
    summary: "Elect three candidates presented by the governance committee for terms beginning July 1.",
    fullMotionText: "Resolved, that the board approves the slate as described in the packet.",
    status: "Scheduled",
    opensAt: "May 4, 2026 — 8:00 a.m.",
    closesAt: "May 6, 2026 — 5:00 p.m.",
    decisionDate: "May 6, 2026",
    meetingDate: "May 6, 2026 — 6:00 p.m.",
    movedBy: "Governance chair",
    secondedBy: "Board secretary",
    owner: "Board coordinator",
    publicVisible: true,
    followUpRequired: false,
    linkedAgendaItem: "Consent agenda — board elections",
    createdAt: "Mar 20, 2026",
    updatedAt: "Apr 28, 2026",
    discussionThread: [
      { id: "c1", author: "Jordan K.", type: "Question", message: "Will candidate bios post 10 days before voting opens?", createdAt: "Apr 25, 2026 — 2:10 p.m." },
      { id: "c2", author: "Board coordinator", type: "Discussion", message: "Yes — portal update scheduled May 1.", createdAt: "Apr 25, 2026 — 4:30 p.m." },
    ],
  },
  {
    id: "cv-2",
    meetingId: "meet-community-may2026",
    title: "Approve revised volunteer policy",
    category: "Policies",
    summary: "Background checks, youth-serving rules, and mileage reimbursement updates.",
    status: "Open for Vote",
    opensAt: "Apr 28, 2026 — 9:00 a.m.",
    closesAt: "May 3, 2026 — 11:59 p.m.",
    decisionDate: "May 4, 2026",
    meetingDate: "May 6, 2026 — 6:00 p.m.",
    movedBy: "Programs director",
    secondedBy: "Vice chair",
    owner: "Board coordinator",
    publicVisible: false,
    followUpRequired: false,
    linkedAgendaItem: "Policy approval — volunteers",
    createdAt: "Apr 1, 2026",
    updatedAt: "Apr 28, 2026",
    discussionThread: [
      { id: "c3", author: "Treasurer", type: "Question", message: "Does mileage match the finance policy appendix?", createdAt: "Apr 29, 2026 — 7:45 a.m." },
    ],
  },
  {
    id: "cv-3",
    meetingId: "meet-community-may2026",
    title: "Approve emergency grant reallocation",
    category: "Finance",
    summary: "Reallocate up to $18,000 to food supplies after vendor shortfall.",
    status: "Draft",
    opensAt: "To be set",
    closesAt: "To be set",
    decisionDate: "Target: May 10, 2026",
    meetingDate: "May 6, 2026 — 6:00 p.m.",
    owner: "Board coordinator",
    publicVisible: true,
    followUpRequired: true,
    notes: "Finance committee finalizing motion — decision timing this week.",
    createdAt: "Apr 27, 2026",
    updatedAt: "Apr 30, 2026",
    discussionThread: [],
  },
  {
    id: "cv-4",
    meetingId: "meet-community-apr8",
    title: "Office lease extension decision",
    category: "Facilities",
    summary: "Three-year renewal option; tabled pending market comparison.",
    status: "Tabled",
    opensAt: "—",
    closesAt: "—",
    decisionDate: "Deferred",
    meetingDate: "Apr 8, 2026",
    owner: "Board coordinator",
    publicVisible: false,
    followUpRequired: true,
    outcome: "Tabled — return in June with broker summary.",
    createdAt: "Mar 5, 2026",
    updatedAt: "Apr 8, 2026",
    discussionThread: [
      { id: "c4", author: "Facilities lead", type: "Discussion", message: "Wait for two comparable quotes before locking escalator.", createdAt: "Apr 7, 2026 — 3:00 p.m." },
    ],
  },
  {
    id: "cv-5",
    meetingId: "meet-community-apr15",
    title: "Approve FY26 insurance renewal",
    category: "Risk",
    summary: "Renewal within budgeted increase.",
    status: "Finalized",
    opensAt: "Apr 10, 2026 — 8:00 a.m.",
    closesAt: "Apr 14, 2026 — 6:00 p.m.",
    decisionDate: "Apr 15, 2026",
    meetingDate: "Apr 15, 2026",
    movedBy: "Treasurer",
    secondedBy: "Chair",
    outcome: "Approved unanimously (consent).",
    votesFor: 11,
    votesAgainst: 0,
    abstentions: 0,
    owner: "Board coordinator",
    publicVisible: false,
    followUpRequired: false,
    finalizedAt: "Apr 15, 2026",
    createdAt: "Mar 28, 2026",
    updatedAt: "Apr 15, 2026",
    discussionThread: [],
  },
  {
    id: "cv-6",
    meetingId: "meet-community-apr8",
    title: "Approve community room use policy",
    category: "Programs",
    summary: "Fee schedule and priority for partner nonprofits.",
    status: "Closed",
    opensAt: "Apr 1, 2026",
    closesAt: "Apr 5, 2026",
    decisionDate: "Apr 8, 2026",
    meetingDate: "Apr 8, 2026",
    outcome: "Approved with amendment to weekend rates.",
    votesFor: 9,
    votesAgainst: 1,
    abstentions: 1,
    owner: "Board coordinator",
    publicVisible: true,
    followUpRequired: false,
    createdAt: "Feb 10, 2026",
    updatedAt: "Apr 8, 2026",
    discussionThread: [
      { id: "c5", author: "Partner advisory rep", type: "Discussion", message: "Clarify cancellation notice for recurring bookings.", createdAt: "Apr 2, 2026 — 11:00 a.m." },
    ],
  },
  {
    id: "cv-7",
    meetingId: "meet-community-may2026",
    title: "Follow-up: grant reporting template",
    category: "Compliance",
    summary: "Unified template across federal and county grants.",
    status: "Needs Follow-Up",
    opensAt: "—",
    closesAt: "—",
    decisionDate: "May 20, 2026",
    owner: "Board coordinator",
    publicVisible: false,
    followUpRequired: true,
    notes: "ED to return with staff proposal in May packet.",
    createdAt: "Apr 8, 2026",
    updatedAt: "Apr 22, 2026",
    discussionThread: [
      { id: "c6", author: "Board chair", type: "Question", message: "Can we see a one-page mock before locking the format?", createdAt: "Apr 20, 2026 — 9:15 a.m." },
    ],
  },
];
