import type { BoardVoteItem } from "../types";

/** Regional Impact Alliance — multi-program growth archetype. */
export const growingBoardVotes: BoardVoteItem[] = [
  {
    id: "gr-1",
    meetingId: "meet-growing-may2026",
    title: "Approve program expansion budget",
    category: "Finance",
    summary: "Phase-in budget for two new workforce cohorts and one health outreach site.",
    status: "Scheduled",
    opensAt: "May 2, 2026 — 7:00 a.m.",
    closesAt: "May 7, 2026 — 6:00 p.m.",
    decisionDate: "May 8, 2026",
    meetingDate: "May 8, 2026 — 5:30 p.m.",
    movedBy: "Finance committee chair",
    secondedBy: "Programs chair",
    owner: "Board coordinator",
    publicVisible: true,
    followUpRequired: false,
    linkedAgendaItem: "Operating budget — program expansion",
    createdAt: "Apr 5, 2026",
    updatedAt: "Apr 29, 2026",
    discussionThread: [
      { id: "g1", author: "Board member", type: "Question", message: "What guardrails if enrollment is below plan by October?", createdAt: "Apr 26, 2026 — 10:20 a.m." },
      { id: "g2", author: "ED", type: "Discussion", message: "Finance attached a trigger table — pause hire #3 if below 85% enrollment.", createdAt: "Apr 27, 2026 — 8:00 a.m." },
    ],
  },
  {
    id: "gr-2",
    meetingId: "meet-growing-may2026",
    title: "Approve leadership restructure proposal",
    category: "Governance",
    summary: "Clarify COO scope and program VP reporting lines.",
    status: "Open for Vote",
    opensAt: "Apr 29, 2026 — 8:00 a.m.",
    closesAt: "May 4, 2026 — 9:00 p.m.",
    decisionDate: "May 5, 2026",
    meetingDate: "May 8, 2026 — 5:30 p.m.",
    movedBy: "Board chair",
    secondedBy: "Governance chair",
    owner: "Board coordinator",
    publicVisible: false,
    followUpRequired: false,
    createdAt: "Apr 10, 2026",
    updatedAt: "Apr 29, 2026",
    discussionThread: [
      { id: "g3", author: "Secretary", type: "Discussion", message: "Recommend a board education moment on delegated authority before the vote closes.", createdAt: "Apr 30, 2026 — 1:00 p.m." },
    ],
  },
  {
    id: "gr-3",
    meetingId: "meet-growing-may2026",
    title: "Approve updated grant compliance policy",
    category: "Compliance",
    summary: "Aligns subrecipient monitoring with new federal guidance.",
    status: "Draft",
    opensAt: "To be set",
    closesAt: "To be set",
    decisionDate: "Target: May 18, 2026",
    owner: "Board coordinator",
    publicVisible: true,
    followUpRequired: true,
    notes: "Counsel review in progress.",
    createdAt: "Apr 20, 2026",
    updatedAt: "Apr 28, 2026",
    discussionThread: [],
  },
  {
    id: "gr-4",
    meetingId: "meet-growing-apr22",
    title: "Approve partnership MOU (county health)",
    category: "Programs",
    summary: "Three-year collaboration on screenings and referrals.",
    status: "Finalized",
    opensAt: "Apr 12, 2026",
    closesAt: "Apr 18, 2026",
    decisionDate: "Apr 20, 2026",
    meetingDate: "Apr 22, 2026",
    movedBy: "ED",
    secondedBy: "Vice chair",
    outcome: "Approved; authorized ED to execute with one legal redline.",
    votesFor: 14,
    votesAgainst: 0,
    abstentions: 1,
    owner: "Board coordinator",
    publicVisible: true,
    followUpRequired: false,
    finalizedAt: "Apr 22, 2026",
    createdAt: "Mar 15, 2026",
    updatedAt: "Apr 22, 2026",
    discussionThread: [
      { id: "g4", author: "Compliance officer", type: "Question", message: "Confirm HIPAA BAAs are attached before signing?", createdAt: "Apr 16, 2026 — 4:00 p.m." },
    ],
  },
  {
    id: "gr-5",
    meetingId: "meet-growing-capital-mar",
    title: "Approve facilities capital plan (trimmed)",
    category: "Operations",
    summary: "Deferred wing renovation; prioritize roof and HVAC package.",
    status: "Closed",
    opensAt: "Mar 20, 2026",
    closesAt: "Mar 25, 2026",
    decisionDate: "Mar 28, 2026",
    outcome: "Approved revised scope; full wing study tabled to Q3.",
    votesFor: 12,
    votesAgainst: 2,
    abstentions: 0,
    owner: "Board coordinator",
    publicVisible: true,
    followUpRequired: false,
    createdAt: "Feb 1, 2026",
    updatedAt: "Mar 28, 2026",
    discussionThread: [],
  },
  {
    id: "gr-6",
    meetingId: "meet-growing-apr15",
    title: "Table: data system consolidation",
    category: "Technology",
    summary: "Vendor selection paused pending county data-sharing agreement.",
    status: "Tabled",
    opensAt: "—",
    closesAt: "—",
    decisionDate: "Deferred",
    owner: "Board coordinator",
    publicVisible: false,
    followUpRequired: true,
    outcome: "Tabled until county MOU is final.",
    createdAt: "Apr 1, 2026",
    updatedAt: "Apr 15, 2026",
    discussionThread: [],
  },
  {
    id: "gr-7",
    meetingId: "meet-growing-may2026",
    title: "Follow-up: development staffing plan",
    category: "Sustainability",
    summary: "Board requested options for adding a major gifts officer.",
    status: "Needs Follow-Up",
    opensAt: "—",
    closesAt: "—",
    decisionDate: "Jun 1, 2026",
    owner: "Board coordinator",
    publicVisible: false,
    followUpRequired: true,
    createdAt: "Apr 18, 2026",
    updatedAt: "Apr 25, 2026",
    discussionThread: [
      { id: "g5", author: "Development chair", type: "Discussion", message: "Leaning toward shared role with partner agency — need board input on risk.", createdAt: "Apr 24, 2026 — 3:30 p.m." },
    ],
  },
];
