import type { BoardVoteItem } from "../types";

/** St. Mark's Academy — private / faith-based archetype. */
export const privateSchoolBoardVotes: BoardVoteItem[] = [
  {
    id: "ps-1",
    meetingId: "meet-school-may2026",
    title: "Approve tuition assistance allocation",
    category: "Access",
    summary: "Annual pool for need-based aid aligned with enrollment targets.",
    status: "Scheduled",
    opensAt: "May 3, 2026 — 6:00 a.m.",
    closesAt: "May 8, 2026 — 8:00 p.m.",
    decisionDate: "May 9, 2026",
    meetingDate: "May 12, 2026 — 7:00 p.m.",
    movedBy: "Advancement chair",
    secondedBy: "Finance chair",
    owner: "Board coordinator",
    publicVisible: true,
    followUpRequired: false,
    linkedAgendaItem: "Tuition and aid",
    createdAt: "Apr 8, 2026",
    updatedAt: "Apr 28, 2026",
    discussionThread: [
      { id: "p1", author: "Board member", type: "Question", message: "How does this affect waitlist families mid-year?", createdAt: "Apr 27, 2026 — 6:00 p.m." },
      { id: "p2", author: "Head of school", type: "Discussion", message: "We hold a small contingency for hardship appeals; process is in the packet addendum.", createdAt: "Apr 28, 2026 — 9:00 a.m." },
    ],
  },
  {
    id: "ps-2",
    meetingId: "meet-school-may2026",
    title: "Approve facilities upgrade phase one",
    category: "Campus",
    summary: "Science labs and HVAC in main building; phase one only.",
    status: "Open for Vote",
    opensAt: "Apr 30, 2026 — 7:00 a.m.",
    closesAt: "May 5, 2026 — 10:00 p.m.",
    decisionDate: "May 6, 2026",
    meetingDate: "May 12, 2026 — 7:00 p.m.",
    movedBy: "Facilities committee chair",
    secondedBy: "Board chair",
    owner: "Board coordinator",
    publicVisible: true,
    followUpRequired: false,
    createdAt: "Apr 12, 2026",
    updatedAt: "Apr 30, 2026",
    discussionThread: [
      { id: "p3", author: "Treasurer", type: "Question", message: "Confirm debt covenant headroom if bids come in high?", createdAt: "May 1, 2026 — 11:15 a.m." },
    ],
  },
  {
    id: "ps-3",
    meetingId: "meet-school-may2026",
    title: "Approve revised parent handbook updates",
    category: "Policy",
    summary: "Communications, attendance, and faith formation expectations.",
    status: "Draft",
    opensAt: "To be set",
    closesAt: "To be set",
    decisionDate: "May 20, 2026",
    owner: "Board coordinator",
    publicVisible: true,
    followUpRequired: true,
    notes: "Parent council feedback due May 10.",
    createdAt: "Apr 22, 2026",
    updatedAt: "Apr 29, 2026",
    discussionThread: [],
  },
  {
    id: "ps-4",
    meetingId: "meet-school-apr2026",
    title: "Approve school calendar adjustment",
    category: "Operations",
    summary: "Move professional day to align with diocesan in-service.",
    status: "Finalized",
    opensAt: "Apr 8, 2026",
    closesAt: "Apr 12, 2026",
    decisionDate: "Apr 14, 2026",
    meetingDate: "Apr 14, 2026",
    outcome: "Approved; published to families Apr 16.",
    votesFor: 13,
    votesAgainst: 0,
    abstentions: 0,
    owner: "Board coordinator",
    publicVisible: true,
    followUpRequired: false,
    finalizedAt: "Apr 14, 2026",
    createdAt: "Mar 25, 2026",
    updatedAt: "Apr 14, 2026",
    discussionThread: [],
  },
  {
    id: "ps-5",
    meetingId: "meet-school-apr2026-b",
    title: "Approve capital campaign feasibility study vendor",
    category: "Advancement",
    summary: "Engage consultant for quiet phase planning.",
    status: "Closed",
    opensAt: "Mar 28, 2026",
    closesAt: "Apr 2, 2026",
    decisionDate: "Apr 5, 2026",
    outcome: "Approved; ED authorized to sign SOW.",
    votesFor: 11,
    votesAgainst: 1,
    abstentions: 1,
    owner: "Board coordinator",
    publicVisible: false,
    followUpRequired: false,
    createdAt: "Mar 1, 2026",
    updatedAt: "Apr 5, 2026",
    discussionThread: [],
  },
  {
    id: "ps-6",
    meetingId: "meet-school-apr2026-c",
    title: "Table: athletics field lighting",
    category: "Campus",
    summary: "Neighbor input incomplete; light pollution study pending.",
    status: "Tabled",
    opensAt: "—",
    closesAt: "—",
    decisionDate: "Deferred",
    owner: "Board coordinator",
    publicVisible: true,
    followUpRequired: true,
    outcome: "Tabled; town hall scheduled May 20.",
    createdAt: "Apr 5, 2026",
    updatedAt: "Apr 18, 2026",
    discussionThread: [
      { id: "p4", author: "Parent rep", type: "Discussion", message: "Request agenda time for traffic and parking impacts.", createdAt: "Apr 17, 2026 — 5:00 p.m." },
    ],
  },
  {
    id: "ps-7",
    meetingId: "meet-school-may2026",
    title: "Follow-up: scholarship endowment transfer",
    category: "Finance",
    summary: "Legal steps to accept restricted gift into endowment.",
    status: "Needs Follow-Up",
    opensAt: "—",
    closesAt: "—",
    decisionDate: "Jun 10, 2026",
    owner: "Board coordinator",
    publicVisible: false,
    followUpRequired: true,
    createdAt: "Apr 19, 2026",
    updatedAt: "Apr 26, 2026",
    discussionThread: [
      { id: "p5", author: "School counsel (note)", type: "Question", message: "Confirm donor intent letter meets diocesan template?", createdAt: "Apr 25, 2026 — 2:00 p.m." },
    ],
  },
];
